# Generated by Django 4.2.11 on 2024-04-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_created_by_post_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='name',
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=65),
        ),
    ]
